services:
  books-reviewer:
    image: ${DOCKER_USER}/myservice:${VERSION}
    build:
      context: .
      args:
        - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    environment:
      - DOCKER_USER=$(mvn help:evaluate -Dexpression=docker.username -q -DforceStdout)