services:
  books-reviewer:
    image: ${DOCKER_USER}/myservice:${VERSION}
    ports:
      - 8080:8080
    build:
      args:
        - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        - DOCKER_USER=$(mvn help:evaluate -Dexpression=docker.username -q -DforceStdout)