name: workflow-release

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Ejecutar pruebas unitarias y de integración
        run: mvn test