#Cuando se esté preparando una release, en la rama release/**:○ Se ejecutarán las pruebas unitarias y de integración por cada commit en larama
name: workflow5
on:
  push:
    branches:
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Ejecutar pruebas unitarias y de integración
        run: mvn test
# Compare this snippet from src\.github\.workflows\workflow1.yml:
