name: workflow3

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Ejecutar todos los test del paquete es.codeurjc.ais
      run: mvn test
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Generate Docker image
      run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/items:v1

    #- name: Build Docker image
      #run: docker build -t myapp:dev-$(date +"%Y-%m-%d") .
      
    - name: Login to DockerHub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
    - name: subir la imagen docker a DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/items:v1
