
name: workflow3

on:
  push:
    branches: [ release-* ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Run Integration test
        run: mvn -B '-Dtest=es.codeurjc.ais.integration.*Test' test
        
      - name: Run Unitary test
        run: mvn -B '-Dtest=es.codeurjc.ais.unitary.*Test' test
        
      - name: Run e2e Rest test
        run: mvn -B '-Dtest=es.codeurjc.ais.e2e.rest.RestTest#getAllBooks test
        
      - name: Run e2e Selenium test
        run:  mvn -B '-Dtest=es.codeurjc.ais.e2e.selenium.*Test' test
        
        
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests 
              -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:${{ github.sha }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:${{ github.sha }}
        
      - name: Install Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
        
      - name: Login into Okteto
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_PASSWORD }}
        
      - name: Deploy to Okteto
        run: |
          export VERSION=${{ github.sha }}
          okteto deploy --wait

      - name: Run e2e Rest sanity test
        run: mvn Dhost=https://books-reviewer-alejandrodelg.cloud.okteto.net/ -B '-Dtest=es.codeurjc.ais.e2e.rest.RestTest#sanityTest test


      
