name: workflow5

on: 
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  deploy_in_okteto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: mvn -B '-Dtest=es.codeurjc.ais.integration.*Test' test
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}" 
      - name: Get Maven version
        id: get_version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:${{steps.get_version.outputs.version }}
      - name: Install Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
      - name: Login into Okteto
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_PASSWORD }}
      - name: Deploy to Okteto
        run: okteto deploy --wait
