name: workflow2

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Run Integration test
        run: mvn -B '-Dtest=es.codeurjc.ais.integration.*Test' test
        
      - name: Run Unitary test
        run: mvn -B '-Dtest=es.codeurjc.ais.unitary.*Test' test
        
      - name: Run e2e Rest test
        run: mvn -B '-Dtest=es.codeurjc.ais.e2e.rest.*Test' test  
      - name: Run e2e Selenium test
        run: mvn -B '-Dtest=es.codeurjc.ais.e2e.selenium.*Test' test  
