
name: workflow4

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          ref: master
          
      - name: Run Integration test
        run: mvn -B '-Dtest=es.codeurjc.ais.integration.*Test' test
        
      - name: Run Unitary test
        run: mvn -B '-Dtest=es.codeurjc.ais.unitary.*Test' test
        
      - name: Run e2e Rest test
        run: mvn -B '-Dtest=es.codeurjc.ais.e2e.rest..getAllBooks' test
        
      - name: Run e2e Selenium test
        run:  mvn -B '-Dtest=es.codeurjc.ais.e2e.selenium.*Test' test
        
      - name: Generar tag
        run: echo ::set-output name=value::$(date +'%Y%m%d.%H%M%S')
        id: timestamp
        
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests 
          -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:dev-${{ steps.timestamp.outputs.value }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:dev-${{ steps.timestamp.outputs.value }}
